// Created by iWeb 3.0.2 local-build-20110324

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,149),url:'22_FunKoLoGy_Annual_General_Meeting_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'22_FunKoLoGy_Annual_General_Meeting_files/stroke_9.png'},{rect:new IWRect(2,-2,115,4),url:'22_FunKoLoGy_Annual_General_Meeting_files/stroke_10.png'},{rect:new IWRect(117,-2,4,4),url:'22_FunKoLoGy_Annual_General_Meeting_files/stroke_11.png'},{rect:new IWRect(117,2,4,149),url:'22_FunKoLoGy_Annual_General_Meeting_files/stroke_12.png'},{rect:new IWRect(117,151,4,5),url:'22_FunKoLoGy_Annual_General_Meeting_files/stroke_13.png'},{rect:new IWRect(2,151,115,5),url:'22_FunKoLoGy_Annual_General_Meeting_files/stroke_14.png'},{rect:new IWRect(-2,151,4,5),url:'22_FunKoLoGy_Annual_General_Meeting_files/stroke_15.png'}],new IWSize(119,153)),stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,196),url:'22_FunKoLoGy_Annual_General_Meeting_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'22_FunKoLoGy_Annual_General_Meeting_files/stroke_1.png'},{rect:new IWRect(2,-2,416,4),url:'22_FunKoLoGy_Annual_General_Meeting_files/stroke_2.png'},{rect:new IWRect(418,-2,4,4),url:'22_FunKoLoGy_Annual_General_Meeting_files/stroke_3.png'},{rect:new IWRect(418,2,4,196),url:'22_FunKoLoGy_Annual_General_Meeting_files/stroke_4.png'},{rect:new IWRect(418,198,4,4),url:'22_FunKoLoGy_Annual_General_Meeting_files/stroke_5.png'},{rect:new IWRect(2,198,416,4),url:'22_FunKoLoGy_Annual_General_Meeting_files/stroke_6.png'},{rect:new IWRect(-2,198,4,4),url:'22_FunKoLoGy_Annual_General_Meeting_files/stroke_7.png'}],new IWSize(420,200))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('22_FunKoLoGy_Annual_General_Meeting_files/22_FunKoLoGy_Annual_General_MeetingMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('../../../../Media/transparent.gif');BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
